/*
 * MultiUserChatUI.java
 *
 * Created on 09 May 2008, 15:22
 */
package xmppclient.multiuserchat;

import xmppclient.*;
import xmppclient.multiuserchat.MultiUserChatInviteUI;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import org.jivesoftware.smack.PacketListener;
import org.jivesoftware.smack.XMPPException;
import org.jivesoftware.smack.packet.Message;
import org.jivesoftware.smack.packet.Packet;
import org.jivesoftware.smack.util.StringUtils;
import org.jivesoftware.smackx.Form;
import org.jivesoftware.smackx.muc.InvitationRejectionListener;
import org.jivesoftware.smackx.muc.MultiUserChat;

/**
 *
 * @author  Lee Boynton (323326)
 */
public class MUCChatUI extends javax.swing.JFrame implements PacketListener
{

    private MultiUserChat muc;

    /** Creates new form MultiUserChatUI */
    public MUCChatUI(String room)
    {
        muc = new MultiUserChat(XMPPClientUI.connection, room + "@conference.192.168.0.8");
        initComponents();
    }

    public void create(String nickname) throws XMPPException
    {
        muc.create(nickname);
        muc.sendConfigurationForm(new Form(Form.TYPE_SUBMIT));
        initialise();
    }

    public void join(String nickname) throws XMPPException
    {
        muc.join(nickname);
        initialise();
    }
    
    @Override
    public void setVisible(boolean b)
    {
        super.setVisible(b);
        pack();
        splitPane.setDividerLocation(0.8);
    }

    private void initialise()
    {
        updateOccupantList();
        muc.addMessageListener(this);
        muc.addParticipantListener(new ParticipantListener());
        muc.addInvitationRejectionListener(new InvitationRejectionListener() 
        {
            @Override
            public void invitationDeclined(String invitee, String reason)
            {
                JOptionPane.showMessageDialog(MUCChatUI.this, 
                        invitee + " rejected your invitation.\nReason: " + reason, 
                        "Invitation rejected", 
                        JOptionPane.INFORMATION_MESSAGE);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        sendTextArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        inviteButton = new javax.swing.JButton();
        splitPane = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextPane = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        memberList = new javax.swing.JList()
        {
            public String getToolTipText(MouseEvent evt)
            {
                // Get item index
                int index = locationToIndex(evt.getPoint());

                // Get item
                String user = (String) getModel().getElementAt(index);

                StringBuilder text = new StringBuilder();
                text.append("<html>");
                text.append(muc.getOccupant(user).getJid());
                text.append("<br>");
                text.append("<strong>Affiliation: </strong>");
                text.append(muc.getOccupant(user).getAffiliation());
                text.append("<br>");
                text.append("<strong>Role: </strong>");
                text.append(muc.getOccupant(user).getRole());
                text.append("</html>");

                // Return the tool tip text
                return text.toString();
            }
        };//);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(muc.getRoom() + " - Conference");
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        sendTextArea.setColumns(20);
        jScrollPane2.setViewportView(sendTextArea);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        inviteButton.setText("Invite");
        inviteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviteButtonActionPerformed(evt);
            }
        });

        messageTextPane.setBackground(new java.awt.Color(255, 255, 255));
        messageTextPane.setEditable(false);
        messageTextPane.setStyledDocument(new ChatTextPaneStyledDocument());
        jScrollPane1.setViewportView(messageTextPane);

        splitPane.setLeftComponent(jScrollPane1);

        memberList.setCellRenderer(new MemberListRenderer());
        jScrollPane3.setViewportView(memberList);

        splitPane.setRightComponent(jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inviteButton)
                    .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inviteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sendButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
    try
    {
        muc.sendMessage(sendTextArea.getText());
        sendTextArea.setText("");
    }
    catch (XMPPException ex)
    {
        Logger.getLogger(MUCChatUI.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_sendButtonActionPerformed

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    int option = JOptionPane.showConfirmDialog(this, 
            "Do you wish to leave the conference?", 
            "Leaving Conference", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);
    
    if(option == JOptionPane.YES_OPTION)
    {
        muc.leave();
        dispose();
    }
}//GEN-LAST:event_formWindowClosing

private void inviteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviteButtonActionPerformed
    
    MultiUserChatInviteUI invite = new MultiUserChatInviteUI(this, true);
    String values[] = invite.showDialog();
    
    if(values[0] == null) return;

    muc.invite(values[0], values[1]);
}//GEN-LAST:event_inviteButtonActionPerformed

    @Override
    public void processPacket(Packet packet)
    {
        Message message = (Message) packet;
        ChatTextPaneStyledDocument doc = (ChatTextPaneStyledDocument) messageTextPane.getStyledDocument();
        doc.insertUser(StringUtils.parseResource(message.getFrom()));
        doc.insertMessage(message.getBody());
    }

    private void updateOccupantList()
    {
        DefaultListModel model = null;

        model = new DefaultListModel();

        Iterator<String> occupants = muc.getOccupants();

        while (occupants.hasNext())
        {
            model.addElement(occupants.next());
        }

        memberList.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inviteButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList memberList;
    private javax.swing.JTextPane messageTextPane;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextArea sendTextArea;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables

    private class ParticipantListener implements PacketListener
    {
        @Override
        public void processPacket(Packet packet)
        {
            updateOccupantList();
        }
    }

    private class MemberListRenderer extends DefaultListCellRenderer
    {
        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus)
        {
            JLabel lbl = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            lbl.setText(StringUtils.parseResource((String) value));
            return lbl;
        }
    }
}
