/*
 * TestSender2.java
 *
 * Created on 08 May 2008, 16:14
 */
package xmppclient.audio;

import java.util.List;
import org.jivesoftware.smack.XMPPConnection;
import org.jivesoftware.smack.XMPPException;
import org.jivesoftware.smack.packet.DefaultPacketExtension;
import org.jivesoftware.smack.packet.Message;
import org.jivesoftware.smack.packet.PacketExtension;

/**
 *
 * @author  Lee Boynton (323326)
 */
public class TestSender extends javax.swing.JFrame
{
    private XMPPConnection connection;
    
    /** Creates new form TestSender2 */
    public TestSender()
    {
        //XMPPConnection.DEBUG_ENABLED = true;
        
        initComponents();
        try
        {
            connection = new XMPPConnection("192.168.0.8");
            connection.connect();
            connection.login("lee", "password");
            Audio audio = new Audio("audio");
            audio.generateListing();
            List<AudioFile> files = audio.getAudioFiles();
            
            Message message = new Message();
            message.setTo("bob@192.168.0.8");
            for(AudioFile file:files)
            {
                DefaultPacketExtension pe = new DefaultPacketExtension("audio","http://bleh.com");
                pe.setValue("name", file.getName());
                message.addExtension(pe);
            }
            connection.sendPacket(message);
        }
        catch (XMPPException ex)
        {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new TestSender();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
