/*
 * TestReceiver2.java
 *
 * Created on 08 May 2008, 16:12
 */
package xmppclient.audio;

import java.util.Collection;
import org.jivesoftware.smack.PacketListener;
import org.jivesoftware.smack.XMPPConnection;
import org.jivesoftware.smack.XMPPException;
import org.jivesoftware.smack.filter.PacketTypeFilter;
import org.jivesoftware.smack.packet.DefaultPacketExtension;
import org.jivesoftware.smack.packet.Message;
import org.jivesoftware.smack.packet.Packet;
import org.jivesoftware.smack.packet.PacketExtension;

/**
 *
 * @author  Lee Boynton (323326)
 */
public class TestReceiver extends javax.swing.JFrame implements PacketListener
{
    private XMPPConnection connection;
    /** Creates new form TestReceiver2 */
    public TestReceiver()
    {
        //XMPPConnection.DEBUG_ENABLED = true;
        
        initComponents();
        try
        {
            connection = new XMPPConnection("192.168.0.8");
            connection.connect();
            connection.login("bob", "password");
            connection.addPacketListener(this, new PacketTypeFilter(Message.class));
        }
        catch (XMPPException ex)
        {
            ex.printStackTrace();
        }
    }
    
    @Override
    public void processPacket(Packet packet)
    {
        System.out.printf("Packet received from %s\n", packet.getFrom());
        for(PacketExtension pe:packet.getExtensions())
        {
            System.out.println(((DefaultPacketExtension)pe).getValue("name"));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new TestReceiver();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
